
package org.universAAL.ontology.rehabontology;

import org.universAAL.middleware.owl.DataRepOntology;
import org.universAAL.middleware.owl.ManagedIndividual;
import org.universAAL.middleware.owl.MergedRestriction;
import org.universAAL.middleware.owl.OntClassInfoSetup;
import org.universAAL.middleware.owl.Ontology;
import org.universAAL.middleware.rdf.Resource;
import org.universAAL.middleware.rdf.TypeMapper;
import org.universAAL.middleware.service.owl.Service;
import org.universAAL.middleware.service.owl.ServiceBusOntology;
import org.universAAL.ontology.RehabontologyFactory;
import org.universAAL.ontology.location.LocationOntology;
import org.universAAL.ontology.phThing.PhThingOntology;
import org.universAAL.ontology.shape.ShapeOntology;
import org.universAAL.ontology.space.SpaceOntology;


/**
 * This class provides the main representation of the rehabontology ontology 
 * for the universAAL platform.
 *
 * @author Generated by the OntologyUML2Java transformation of AAL Studio
 */
public final class RehabontologyOntology extends Ontology {

  private static RehabontologyFactory factory = new RehabontologyFactory();
  public static final String NAMESPACE ="http://ontology.universAAL.org/RehabOntology#";
	
  public RehabontologyOntology() {
    super(NAMESPACE);
  }

  public void create() {
    Resource r = getInfo();
    r.setResourceComment("Testing ontology");
    r.setResourceLabel("rehabontology");
    addImport(DataRepOntology.NAMESPACE);
    addImport(ServiceBusOntology.NAMESPACE);
    addImport(LocationOntology.NAMESPACE);
    addImport(PhThingOntology.NAMESPACE);
    addImport(ShapeOntology.NAMESPACE);
    addImport(SpaceOntology.NAMESPACE);
    // TODO: Add any additionally imported ontologies here
    

    // ******* Declaration of regular classes of the ontology ******* //
    OntClassInfoSetup oci_ExerciseResults = createNewOntClassInfo(ExerciseResults.MY_URI, factory, 0);
    OntClassInfoSetup oci_ExerciseAnalyser = createNewOntClassInfo(ExerciseAnalyser.MY_URI, factory, 1);

    // ******* Add content to regular classes of the ontology ******* //
    oci_ExerciseResults.setResourceComment("");
    oci_ExerciseResults.setResourceLabel("ExerciseResults");
    oci_ExerciseResults.addSuperClass(ManagedIndividual.MY_URI); 
    oci_ExerciseResults.addDatatypeProperty(ExerciseResults.PROP_RESULTS).setFunctional();
      	oci_ExerciseResults.addRestriction(MergedRestriction.getAllValuesRestriction(ExerciseResults.PROP_RESULTS,  
       	TypeMapper.getDatatypeURI(Long.class)));
    oci_ExerciseResults.addDatatypeProperty(ExerciseResults.PROP_TIME).setFunctional();
      	oci_ExerciseResults.addRestriction(MergedRestriction.getAllValuesRestriction(ExerciseResults.PROP_TIME,  
       	TypeMapper.getDatatypeURI(Long.class)));

    oci_ExerciseAnalyser.setResourceComment("");
    oci_ExerciseAnalyser.setResourceLabel("ExerciseAnalyser");
    oci_ExerciseAnalyser.addSuperClass(Service.MY_URI); 
    oci_ExerciseAnalyser.addObjectProperty(ExerciseAnalyser.PROP_EXERCISE_RESULTS).setFunctional();
    oci_ExerciseAnalyser.addRestriction(MergedRestriction
      .getAllValuesRestrictionWithCardinality(ExerciseAnalyser.PROP_EXERCISE_RESULTS, 
          ExerciseResults.MY_URI, 1, 1));

  }
}
